### ISSUE TITLE
Problems when toggling bypass-mode with shortcut

### ISSUE THREAD

**Issue by DarioViva42** [MaxGyver83/neo2-llkh#11]
Hello @MaxGyver83 

I wanted to find out the key-combination, which toggles the bypass mode.
So I went along, looked into the code of main.c and found the relevant part on line 608.
There it was configured that it toggles the mode when <kbd>Shift</kbd> + <kbd>Pause</kbd> was pressed.
So the problem is that my laptop has no <kbd>Pause</kbd> key, so I changed it to use <kbd>Esc</kbd> instead.
```c
	if (code == HC_ACTION && wparam == WM_KEYDOWN &&
		shiftPressed && keyInfo.scanCode == 1) {
		// Shift + Esc
		toggleBypassMode();
		return -1;
	}
```
So far so good, but then I tested it, and was surprised. After releasing both keys and then pressing <kbd>Esc</kbd> by itself, it toggled the bypass mode. I was perplexed, why is it toggling? I didn't press <kbd>Shift</kbd>.
After testing some more, I realised that this was only happening, when the shortcut resulted in activating the bypass mode. If the bypass mode gets deactivated before releasing both keys, then the <kbd>Esc</kbd> alone works as expected (does not toggle).

So what is happening here and how can I solve it?

I already tried putting `shiftPressed = false` into the method, but then other problems occurred.

Kind regards from Switzerland

Dario Viva

PS:
I also designed other icons for the system tray. Feel free to use them.
[icons.zip](https://github.com/MaxGyver83/neo2-llkh/files/5059586/icons.zip)

**Comment by MaxGyver83** [comment]
Hi Dario,

thanks for reporting! Indeed, it's not behaving as expected. I didn't notice before because I never use the bypass mode. I'll need some time to understand what's going wrong here.

Best regards
Max

**Comment by DarioViva42** [comment]
Hey Max

Ich denke, ich weiss warum das so fehlerhaft ist. Auf [https://github.com/david0/neo2-llkh/tree/master/src](url) ist zu sehen, dass der Code erst ein Jahr nach dem Rest implementiert wurde. Und dass das auch der einzige Pullrequest war [https://github.com/david0/neo2-llkh/pull/3](url) der obendrauf nicht von David selbst geschrieben wurde.

Da ist es verständlich, dass Fehler passieren können. Ich werde versuchen dort auch jamanden zu erreichen. Aber das ist halt auch schon 5 Jahre her, ob dort noch jemand aktiv reinschaut?

Also wenn du Zeit hast und es herausfindest wäre das natürlich super. Denn mit einem Shortcut zu toggeln wär glaub schon nicht nur für mich ne schöne Sache.

Grüsse

Dario

**Comment by thomasgm1971** [comment]
hallo,

ich benutze shift pause regelmässig, um zwischendurch immer mal auf qwertz zu wechseln. dabei hatte ich noch nie probleme. ich lasse den neo-llkh aber als admin laufen. dabei verschwindet das icon im tray-bereich nach einigen tagen (aber nur bei run as admin), so dass ich auf den shortcut angewiesen bin.

liebe grüsse,
thomas

**Comment by DarioViva42** [comment]
Hallo @thomasgm1971 

Ja es funktioniert schon, aber eben nicht so wie es soll. Wenn du <kbd>Shift</kbd> + <kbd>Pause</kbd> drückst um den bypass-modus zu aktivieren (also auf qwertz wechselst), dann funktioniert das zwar. Aber danach kannst du den <kbd>Pause</kbd> Knopf alleine drücken und er wird den Modus wieder umschalten. Bei <kbd>Pause</kbd> ist das nicht so schlimm weil man diesen Knopf sonst nicht wirklich benutzt. Aber auf einem Laptop möchte man den Shortcut ummappen, damit man ihn benutzen kann. Ich wollte es z.B. auf <kbd>Win</kbd> + <kbd>Space</kbd> mappen. So kam ich auch auf den Bug. Jedes mal wenn man die Leertaste drückt, ändert man den Modus.

Ich lasse es auch als Admin laufen, da sonst Programme wie Regedit nicht auf VOU reagieren, hat also nichts damit zu tun.

Liebe Grüsse

Dario

**Comment by thomasgm1971** [comment]
hallo,

dario, das kann ich so bestätigen! die pause taste benutze ich sonst
überhaupt nicht.
mir ist eben aufgefallen, wenn man mit shift pause auf dem qwertz-modus
ist, passiert es, wenn ich dann ohne shift mit nur pause wieder auf den
neo-modus gehe, kommen alles grossbuchstaben und die zahlenreihe geshiftet
(aber eben nicht im qwertz-modus). da scheint das shift irgendwo zu hängen?
wenn ich dann im neo modus die shift taste kurz anschlage, ist der spuk
verschwunden. aber leider funktioniert das nicht, während man noch im
qwertz-modus ist... ergo kein workaround :-( als ob das shift im
neo-llkh hängen würde, und nur dort.

liebe grüsse
thomas

Am Fr., 14. Aug. 2020 um 21:12 Uhr schrieb Dario Viva <
notifications@github.com>:

**Comment by MaxGyver83** [comment]
Ich weiß jetzt zumindest, woran es liegt: Wenn der Bypass-Modus aktiviert wird, ist die Variable `shiftPressed` = `true`. Im Bypass-Modus bleibt der Wert dann wie er ist.

> I already tried putting `shiftPressed = false` into the method, but then other problems occurred.

Das hilft auch nicht, weil `shiftPressed` dann dauerhaft `false` ist und so der Bypass-Modus nicht beendet werden kann.

Ich hoffe, ich finde eine einfache Lösung.

**Comment by MaxGyver83** [comment]
This version should fix the bypass mode: https://maximilian-schillinger.de/neo-llkh-bugfix-bypass-mode.exe

Could you test it, please?

**Comment by DarioViva42** [comment]
very nice, thank you that works!

ich weiss ja nicht warum wir hier überhaupt auf englisch miteinander reden, wir reden hier über ein Layout mit deutschen Umlauten, als ob das jemand benutzen wollte, der kein Deutsch kann. 🤣

naja eigentlich egal, aber so wie es aussieht funktioniert dieses .exe
vielen grossen Dank dass du dir das so zeitnah angeschaut hast, du hättest den Pro Titel von Github ehr und redlich verdient. 🥇

Kann ich noch den Code sehen, damit ich auch testen kann ob es mit anderen Knöpfen funktioniert. Hoffentlich ist es nicht auf die Umschalt-Taste begrenzt. <kbd>Win</kbd>+<kbd>Space</kbd> wär da schon mein Favorit, da der auch schon von Windows selbst verwendet wird um Tastaturlayouts zu wechseln. 

Ausserdem besteht bei dem Pause-Knopf noch das Problem, dass er den selben Keycode wie der Num Lock Key besitzt. Das habe ich auch auf deiner Seite mit den Keycodes gesehen. Und daher kann man mit der Num Lock Taste auch den Modus umschalten. Das ist jetzt nicht tragisch, aber sauber wäre wie du in #15 beschrieben hast den extended key code einzulesen.

> Scan code 32 is 0x20 (as hex). This [page](http://www.winfaq.de/faq_html/Content/tip1500/onlinefaq.php?h=tip1576.htm) says that 0x20 is the D key and you get an "A" because that's on the D key in Neo. It also says that 0x20E0 is VolumeMute. That's the same scan code but with the extended bit set. You can see a 0x1 in the `neo-llkh` debug output. I think that this is just being ignored. I guess, I can fix this.

Freundliche Grüsse

Dario

**Comment by MaxGyver83** [comment]
> I also designed other icons for the system tray. Feel free to use them.

Danke für die Icons! Die sehen gut aus!

> Kann ich noch den Code sehen, damit ich auch testen kann ob es mit anderen Knöpfen funktioniert.

Hier ist der Code: https://github.com/MaxGyver83/neo2-llkh/pull/19/files
`Shift`+`Pause` ist fest kodiert. Du könntest das natürlich im Quellcode ändern und selbst kompilieren. Wenn du den Shortcut `Win`+`Leertaste` verwenden willst, könnte das sehr kompliziert werden, wenn du gleichzeitig die Option `swapLeftCtrlLeftAltAndLeftWin` verwendest, weil dann im Bypass Mode die Tasten nicht mehr vertauscht werden und dann das Lösen der Windows-Taste nicht mehr erfasst wird. Prinzipiell müsstest du überhaupt erst einmal die Änderungen, die ich jetzt für die Shift-Tasten gemacht habe, für die Windows-Tasten durchführen (also die Übewachung auch im Bypass Mode).

> Ausserdem besteht bei dem Pause-Knopf noch das Problem, dass er den selben Keycode wie der Num Lock Key besitzt.

Das Problem hab ich jetzt gelöst, indem ich auf den Virtual Key Code statt auf den Scan Code schaue. Der ist für Pause und NumLock unterschiedlich.
