### ISSUE TITLE
Enter/Return with alt-right + "v" does not always work

### ISSUE THREAD

**Issue by korbinian90** [MaxGyver83/neo2-llkh#13]
Another problem I ran into:

When I try to press Return via alt-right + "v" often nothing happens, I can press as often as I want. Only after pressing "Enter" two times it starts working.

Debug Log:
I placed the curser in a new window (google notes in chrome)
and tried to press Return via alt-right + "v" -> nothing happens
I press "Enter" on the keyboard -> nothing happens
I press "Enter" on the Keyboard again -> new line appears
I press alt-right + "v" -> new line appears

 Layout: neo
 symmetricalLevel3Modifiers: 0
 returnKeyAsMod3R: 0
 tabKeyAsMod4L: 0
 capsLockEnabled: 1
 shiftLockEnabled: 0
 level4LockEnabled: 0
 qwertzForShortcuts: 1
 swapLeftCtrlAndLeftAlt: 0
 swapLeftCtrlLeftAltAndLeftWin: 0
 supportLevels5and6: 1
 capsLockAsEscape: 0
 mod3RAsReturn: 0
 mod4LAsTab: 0
 debugWindow: 1

key down  sc 541 vk 0xa2 0x20 0 (Ctrl left)

key down  sc 56 vk 0xa5 0x21 0 (Alt right)
injected   sc 541 vk 0xa2 0x90 0 (Ctrl left)
injected   sc 0 vk 0xa5 0x90 0 (Alt right)

key down  sc 47 vk 0x56 0x0 0 (A-Z)
injected   sc 0 vk 0xd 0x11 0 (Return)
key up     sc 47 vk 0x56 0x80 0 (A-Z)
key up     sc 541 vk 0xa2 0x80 0 (Ctrl left)
key up     sc 56 vk 0xa5 0x81 0 (Alt right)

key down  sc 28 vk 0xd 0x0 0 (Return)
key up     sc 28 vk 0xd 0x80 0 (Return)

key down  sc 28 vk 0xd 0x0 0 (Return)
key up     sc 28 vk 0xd 0x80 0 (Return)

key down  sc 541 vk 0xa2 0x20 0 (Ctrl left)

key down  sc 56 vk 0xa5 0x21 0 (Alt right)
injected   sc 541 vk 0xa2 0x90 0 (Ctrl left)
injected   sc 0 vk 0xa5 0x90 0 (Alt right)

key down  sc 47 vk 0x56 0x0 0 (A-Z)
injected   sc 0 vk 0xd 0x11 0 (Return)
key up     sc 47 vk 0x56 0x80 0 (A-Z)
key up     sc 541 vk 0xa2 0x80 0 (Ctrl left)
key up     sc 56 vk 0xa5 0x81 0 (Alt right)

**Comment by MaxGyver83** [comment]
That's even stranger than your other bug :smile: 

The debugging output looks like `AltGr+v` is being sent the same way twice and same for the physical `Enter` key. I have no idea why Chromes accepts the input sometimes and sometimes it doesn't. I don't know how to fix this.

**Comment by MaxGyver83** [comment]
What you could try:

* Open the developer tools in Chrome (press F12) when you are in Google Notes.
* Select the Console and enter: `document.addEventListener('keydown', e => console.log(e), true);`
* Focus the browser main window.
* Press `AltGr+v` and `Enter` and other keys and observe the console output.

**Comment by korbinian90** [comment]
It also happens here, when answering. I can reliably reproduce it on my machine, when I click with the mouse outside the window and then to where I want to write and press `AltGr+v`. I couldn't reproduce the problem in Firefox, notepad or MS Word, so it seems to be only Chrome related. I tested with and without quertzForShortcuts and the problem occurs in both configurations.

I tested in Chrome (google notes), but couldn't find anything strange myself. Here is the output:
![image](https://user-images.githubusercontent.com/1307522/90224809-8e82c800-de10-11ea-8757-81aa82967688.png)
I pressed 2 times `AltGr+v` (nothing happens)
then 2 times `Enter` then (the second one produces a newline)
then `AltGr+v` (a new line appears)

More detail for the log output:
![image](https://user-images.githubusercontent.com/1307522/90225475-bcb4d780-de11-11ea-86a4-357854dec44d.png)
![image](https://user-images.githubusercontent.com/1307522/90225347-7cedf000-de11-11ea-863f-ef9626c614a8.png)
![image](https://user-images.githubusercontent.com/1307522/90225365-870fee80-de11-11ea-813b-f6dd6040dbdb.png)
![image](https://user-images.githubusercontent.com/1307522/90225383-9000c000-de11-11ea-8289-4dac6e4d6010.png)

**Comment by MaxGyver83** [comment]
The only difference I see is that `AltGr+v` is seen as `key: "Enter", code: ""` and `Enter` is seen as `key: "Enter", code: "Enter"`.

I made a test version that sends `code: "Enter"` for `AltGr+v`: https://maximilian-schillinger.de/neo-llkh-enter.exe

Please tell me if this solves your issue!

**Comment by korbinian90** [comment]
Thanks for compiling the new version. Unfortunately it is still the same issue. In chrome I see that it sends `code: "Enter"`.
As it appears only in chrome (and chrome apps like hangouts), and it's easy to fix with pressing `Enter`, it's no big problem.

**Comment by korbinian90** [comment]
problem also in visual studio code

**Comment by fw623** [comment]
> problem also in visual studio code

You can try [this workaround](https://github.com/microsoft/vscode/issues/24043#issuecomment-292334048) if you haven't tried it already.

**Comment by korbinian90** [comment]
> You can try this workaround if you haven't tried it already.

Thanks for the suggestion!
I tried it, but the `"keyboard.dispatch"` setting doesn't seem to exist in VSCode 1.48.2 under Windows 10: `Unknown Configuration Setting`. 

And following along the thread I found someone else who [doesn't have the setting](https://github.com/microsoft/vscode/issues/24043#issuecomment-375925882), but unfortunately no other solution for that case.

**Comment by MaxGyver83** [comment]
Apparently, this setting is only valid for Mac and Linux: https://github.com/microsoft/vscode/issues/102570#issuecomment-659693178

Keybindings are handled differently in Windows, Linux and MacOS: https://github.com/microsoft/vscode/wiki/Keybinding-Issues

Do you have the same issue with [NeoVars](https://git.neo-layout.org/neo/neo-layout/wiki/Neo-unter-Windows-einrichten-(NeoVars))?
