### ISSUE TITLE
Special volume keys on notebook not working

### ISSUE THREAD

**Issue by korbinian90** [MaxGyver83/neo2-llkh#15]
On my notebook I found another minor issue:
Pressing the disable sound button (own physical key) or the increase/decrease volume buttons (function keys F9/F8), they produce normal keystrokes:

decrease sound: ä
increase sound: z
disable sound: a

Here is the debuglog:
(It is strange that the deguglog says ö, but ä appears)

Einstellungen aus C:\Users\korbi\Desktop\settings.ini:
 Layout: neo
 symmetricalLevel3Modifiers: 0
 returnKeyAsMod3R: 0
 tabKeyAsMod4L: 0
 capsLockEnabled: 0
 shiftLockEnabled: 0
 level4LockEnabled: 0
 qwertzForShortcuts: 1
 swapLeftCtrlAndLeftAlt: 0
 swapLeftCtrlLeftAltAndLeftWin: 0
 supportLevels5and6: 0
 capsLockAsEscape: 0
 mod3RAsReturn: 0
 mod4LAsTab: 0
 debugWindow: 1

key down  sc 46 vk 0xae 0x1 0
Mapped 46  ->õ [0x00E4] (level 1)
injected   sc 46 vk 0xde 0x11 0
key up     sc 46 vk 0xae 0x81 0

key down  sc 48 vk 0xaf 0x1 0
Mapped 48  ->z [0x007A] (level 1)
injected   sc 48 vk 0x5a 0x11 0 (A-Z)
key up     sc 48 vk 0xaf 0x81 0

key down  sc 32 vk 0xad 0x1 0
Mapped 32  ->a [0x0061] (level 1)
injected   sc 32 vk 0x41 0x11 0 (A-Z)
key up     sc 32 vk 0xad 0x81 0

**Comment by DarioViva42** [comment]
@korbinian90 @MaxGyver83 

![grafik](https://user-images.githubusercontent.com/45972949/90445134-798f8880-e0df-11ea-9cb3-62891b95b228.png)

There are other Function-Keys that dont work.

**Comment by MaxGyver83** [comment]
On my laptop, the media keys work as expected. My output for _VolumeDown_, _VolumeUp_, _VolumeMute_:

```
injected   sc 0 vk 0xae 0x11 0
injected   sc 0 vk 0xae 0x91 0
injected   sc 0 vk 0xaf 0x11 0
injected   sc 0 vk 0xaf 0x91 0
injected   sc 0 vk 0xad 0x11 0
injected   sc 0 vk 0xad 0x91 0
```

I'm going to try the same with your configuration...

@DarioViva42: Where is this table from?

**Comment by MaxGyver83** [comment]
Which version of neo-llkh do you use?

**Comment by korbinian90** [comment]
I had the issue with both the compiled version v0.3 and with neo-llkh-enter.exe

**Comment by MaxGyver83** [comment]
I start understanding it:

> key down sc 32 vk 0xad 0x1 0
Mapped 32 ->a [0x0061] (level 1)
injected sc 32 vk 0x41 0x11 0 (A-Z)
key up sc 32 vk 0xad 0x81 0

Scan code 32 is 0x20 (as hex). This [page](http://www.winfaq.de/faq_html/Content/tip1500/onlinefaq.php?h=tip1576.htm) says that 0x20 is the D key and you get an "A" because that's on the D key in Neo. It also says that 0x20E0 is VolumeMute. That's the same scan code but with the extended bit set. You can see a 0x1 in the `neo-llkh` debug output. I think that this is just being ignored. I guess, I can fix this.

**Comment by MaxGyver83** [comment]
Could you test if this fixes your problem with the media keys?
http://maximilian-schillinger.de/neo-llkh-media-keys.exe

**Comment by DarioViva42** [comment]
@MaxGyver83 

also die Tabelle habe ich erstellt mit dem [Keyboard Event Viewer](https://w3c.github.io/uievents/tools/key-event-viewer.html). Mithilfe von dem kam ich auf das Problem in #17.

Und @korbinian90 

wollen wir nicht lieber deutsch reden, geht das nicht einfacher für alle hier? 
Ich meine das Readme von Max ist auch auf Deutsch.

und ich hab dir noch einen pedantischen Tipp: 
, or? als Fragenanhängsel gibt es so im Englischen nicht, bist aber nicht der einzige der darauf reingefallen ist. [Link zu Thread auf Leo](https://dict.leo.org/forum/viewUnsolvedquery.php?idForum=1&idThread=1046967&lp=ende&lang=de)

Viele Grüsse nach Stuttgart und Wien aus der Schweiz

Dario

**Comment by DarioViva42** [comment]
![grafik](https://user-images.githubusercontent.com/45972949/90687364-09167200-e26d-11ea-8d8b-623ed860a10d.png)

Mega gut! Dieses .exe funktioniert auch. Du eliminierst einen Fehler nach dem anderen als wäre es nichts.
LaunchApplication2 ist standartmässig übrigens der Windows Calculator in Win.

**Comment by korbinian90** [comment]
Wow, sehr cool!
Bei mir funktionieren die Media Keys auch mit der neuen Version!

@DarioViva42 haha, ich bin irgendwie nicht auf die Idee gekommen auf deutsch zu schreiben. Und danke für den Tipp ;)

**Comment by MaxGyver83** [comment]
> also die Tabelle habe ich erstellt mit dem Keyboard Event Viewer.

Cool, schau ich mir mal an!

> wollen wir nicht lieber deutsch reden, geht das nicht einfacher für alle hier?

Kein Problem. Ich hab nur auf Englisch geantwortet, weil die Frage auf Englisch war.

> Bei mir funktionieren die Media Keys auch mit der neuen Version!

Sehr gut! Dann kommt das in die offizielle Version.
