### ISSUE TITLE
Key combination Alt+caps-lock does not work

### ISSUE THREAD

**Issue by korbinian90** [MaxGyver83/neo2-llkh#16]
One thing that is amazing is that I can type Japanes input with neo2-llkh (either via Google IME or Microsoft IME), which doesn't work with the neo ahk driver.

One issue that I have with Google IME is that the key combination `Alt+Caps-lock` is supposed to switch the input mode, but seems to only act as `Alt`. I tried it with quertzForShortcuts on and off.

My workarounds are either using Microsoft IME with a different shortcut or pressing the button with the mouse in Google IME.

Debug output for pressing the key combination `Alt+Caps-lock` (alt down, caps-lock down, caps-lock up, alt up)

Einstellungen aus C:\Users\korbi\Desktop\settings.ini:
 Layout: neo
 symmetricalLevel3Modifiers: 0
 returnKeyAsMod3R: 0
 tabKeyAsMod4L: 0
 capsLockEnabled: 0
 shiftLockEnabled: 0
 level4LockEnabled: 0
 qwertzForShortcuts: 0
 swapLeftCtrlAndLeftAlt: 0
 swapLeftCtrlLeftAltAndLeftWin: 0
 supportLevels5and6: 0
 capsLockAsEscape: 0
 mod3RAsReturn: 0
 mod4LAsTab: 0
 debugWindow: 1

key down  sc 56 vk 0xa4 0x20 0 (Alt left)
injected   sc 0 vk 0xa4 0x30 0 (Alt left)
key up     sc 58 vk 0xf0 0xa0 0

key down  sc 58 vk 0xf1 0x20 0
key up     sc 56 vk 0xa4 0x80 0 (Alt left)
injected   sc 0 vk 0xa4 0x90 0 (Alt left)

**Comment by MaxGyver83** [comment]
Well, that's not a bug. In Neo, CapsLock is mapped to the level 3 modifier. So there is no CapsLock key in that layout and Alt+CapsLock is not available. I'm happy you found some workarounds. Another workaround could be to use to go back to QWERTZ for pressing Alt+CapsLock and then back to Neo.

**Comment by korbinian90** [comment]
You are right... because you can press Alt+M3+"key on level 3". So there is unfortunately no solution for neo. Then I will keep using Microsoft IME for japanese, as the other options are not as convenient.
Thanks for answering!

**Comment by korbinian90** [comment]
I just realized that, when using the qwertz shortcut option, then the shortcut `Alt+CapsLock` could/should be available, or?

**Comment by MaxGyver83** [comment]
No, then CapsLock is still a layer 3 modifier.

**Comment by korbinian90** [comment]
Hm, but in qwertz-shortcut mode M3 has no function in the context of pressing Left-Alt or Left-Ctrl or?

**Comment by MaxGyver83** [comment]
No, nothing should happen if you only press Alt+Mod3 or Ctrl+Mod3. It's the same for other modifiers. If you press Ctrl+Alt or Win+Shift, nothing happens.

**Comment by korbinian90** [comment]
Ok, as it is intended behavior, I close the issue again.
