### ISSUE TITLE
[Feature] Enter einhändig für linke Hand

### ISSUE THREAD

**Issue by korbinian90** [MaxGyver83/neo2-llkh#20]
Ich benutze jetzt nur noch deine neo Variante und bin sehr glücklich damit!
Eine Sache die ich oft mache ist mit der rechten Hand mit der Maus etwas auswählen und mit der linken Hand `Strg+C`, `Strg+V`, `Strg+T` und co zu verwenden. Eine Sache die hier noch sehr praktisch wäre, wäre eine Möglichkeit für `Return` mit der linken Hand. 
Da es die Option gibt den rechten M3 Modifier als Return zu verwenden, wäre meine Idee den linken auch als Return zu verwenden, wenn man ihn alleine drückt. Was haltet ihr davon?

**Comment by thomasgm1971** [comment]
guten morgen

nette idee, aber die linke m3 allein gedrückt ist schon mit escape
belegt, und wir vereinigten vim-mer gehen auf die barrikaden, wenn das
wegfällt :-) aber konfigurierbar, warum nicht?

thomas

Am Fr., 21. Aug. 2020 um 07:37 Uhr schrieb Korbinian Eckstein
<notifications@github.com>:

**Comment by MaxGyver83** [comment]
Warum benutzt du nicht einfach `<`+`v` (bzw. `c`) mit der linken Hand?

**Comment by korbinian90** [comment]
Danke für die super schnellen Antworten!
`<`+`v` ist eine gute Lösung, ich denke zwei Tasten sind auch nicht zu umständlich.

Danke für die Lösung und sorry, dass ich nicht selber drauf gekommen bin und euch damit nerve.
