### ISSUE TITLE
"mod4LAsTab=1" funktioniert nicht richtig

### ISSUE THREAD

**Issue by thomasgm1971** [MaxGyver83/neo2-llkh#21]
hallo max,

wenn ich mod4l als tab benutze, bleibt danach die ebene 4 hängen, obwohl ich sogar das ebene4-lock deaktiviert habe. noch mehr drücke auf mod4l lösen das hängen nicht, bringen aber tab-zeichen wie gewünscht. lösen lässt sich der ebenen-4-hänger nur durch kurzes drücken von mod4r oder durch mod4l in verbindung (!) mit einer anderen taste. so ist das mod4l-tab leider recht unbrauchbar.
das passiert sowohl als user als auch als admin. im log ist nur das lösen mit mod4r drin, ich hoffe das reicht?

ansonsten danke für neo2-llkh!!!
einen schönen abend, thomas

Einstellungen aus C:\Users\thomas\Desktop\_tmp\neo2-llkh_0.3\settings.ini:
 Layout: neo
 symmetricalLevel3Modifiers: 0
 returnKeyAsMod3R: 0
 tabKeyAsMod4L: 0
 capsLockEnabled: 1
 shiftLockEnabled: 0
 level4LockEnabled: 0
 qwertzForShortcuts: 0
 swapLeftCtrlAndLeftAlt: 1
 swapLeftCtrlLeftAltAndLeftWin: 0
 supportLevels5and6: 0
 capsLockAsEscape: 1
 mod3RAsReturn: 1
 mod4LAsTab: 1
 debugWindow: 1

key down  sc 36 vk 0x4a 0x0 0 (A-Z)
Mapped 36 J->n [0x006E] (level 1)
injected   sc 36 vk 0x4e 0x12 0 (A-Z)
key up     sc 36 vk 0x4a 0x80 0 (A-Z)

key down  sc 86 vk 0xe2 0x0 0 (M4 left [<])

key down  sc 36 vk 0x4a 0x0 0 (A-Z)
Mapped 36 J->4 [0x0034] (level 4)
injected   sc 36 vk 0x34 0x12 0
key up     sc 36 vk 0x4a 0x80 0 (A-Z)
key up     sc 86 vk 0xe2 0x80 0 (M4 left [<])

key down  sc 86 vk 0xe2 0x0 0 (M4 left [<])
key up     sc 86 vk 0xe2 0x80 0 (M4 left [<])
injected   sc 0 vk 0xe2 0x92 0 (M4 left [<])
injected   sc 0 vk 0x9 0x13 0

key down  sc 36 vk 0x4a 0x0 0 (A-Z)
Mapped 36 J->4 [0x0034] (level 4)
injected   sc 36 vk 0x34 0x12 0
key up     sc 36 vk 0x4a 0x80 0 (A-Z)

key down  sc 86 vk 0xe2 0x0 0 (M4 left [<])
key up     sc 86 vk 0xe2 0x80 0 (M4 left [<])
injected   sc 0 vk 0xe2 0x92 0 (M4 left [<])
injected   sc 0 vk 0x9 0x13 0

key down  sc 36 vk 0x4a 0x0 0 (A-Z)
Mapped 36 J->4 [0x0034] (level 4)
injected   sc 36 vk 0x34 0x12 0
key up     sc 36 vk 0x4a 0x80 0 (A-Z)

key down  sc 541 vk 0xa2 0x20 0 (Ctrl left)

key down  sc 56 vk 0xa5 0x21 0 (Alt right)
key up     sc 541 vk 0xa2 0x80 0 (Ctrl left)
injected   sc 0 vk 0xa5 0x92 0 (Alt right)
key up     sc 541 vk 0xa2 0x80 0 (Ctrl left)
key up     sc 56 vk 0xa5 0x81 0 (Alt right)

key down  sc 36 vk 0x4a 0x0 0 (A-Z)
Mapped 36 J->n [0x006E] (level 1)
injected   sc 36 vk 0x4e 0x12 0 (A-Z)
key up     sc 36 vk 0x4a 0x80 0 (A-Z)

key down  sc 36 vk 0x4a 0x0 0 (A-Z)
Mapped 36 J->n [0x006E] (level 1)
injected   sc 36 vk 0x4e 0x12 0 (A-Z)
key up     sc 36 vk 0x4a 0x80 0 (A-Z)

**Comment by MaxGyver83** [comment]
Hallo Thomas,

danke für den Fehlerbericht. Ich versuch morgen, das nachzustellen!

Grüße
Max

**Comment by MaxGyver83** [comment]
Hallo Thomas,

du hast recht, das hat nicht richtig funktioniert. Ich hab die Funktion selbst nie benutzt und es deshalb gar nicht bemerkt.

Ich hab den Fehler gefunden. Damit sollte es funktionieren: [neo-llkh-mod4LAsTab.exe](https://maximilian-schillinger.de/neo-llkh-mod4LAsTab.exe)

Wenn es bei dir auch wie erwartet funktioniert, mach ich ein neues Release.

Grüße
Max

**Comment by thomasgm1971** [comment]
hallo max,

danke für die schnelle reaktion! und.es funktioniert tadellos, ich habe
eben mehrere stunden damit geschrieben. perfekt!

wünsche dir einen schönen abend
thomas

Am Sa., 29. Aug. 2020 um 10:03 Uhr schrieb Max <notifications@github.com>:

**Comment by MaxGyver83** [comment]
Danke, wünsch ich dir auch!
