### ISSUE TITLE
 `~`, `"` , `'` on level 3 behave like dead keys

### ISSUE THREAD

**Issue by MaxGyver83** [MaxGyver83/neo2-llkh#25]
`~`, `"` , `'` on level 3 behave like dead keys!

(Reminder to myself.)

**Comment by MaxGyver83** [comment]
My bad: My keyboard layout was set to English (USA or International).

**Comment by DarioViva42** [comment]
@MaxGyver83 
auf der schweizer tastatur ist zwar nur das ~ ein totes zeichen aber trotzdem nervig.
eventuell macht es sinn in die anleitung zu schreiben, dass man das system layout auf Deusch (Deutschland) setzen sollte, mit einem hinweis, dass sonst einige zeichen nicht richtig funktionieren werden.
