### ISSUE TITLE
Zusätzliche Ebenen von / bei Numberpad funktionieren nicht

### ISSUE THREAD

**Issue by DarioViva42** [MaxGyver83/neo2-llkh#28]
Nachdem nun der Pull Request Nummer 14 gemerged wurden, funktionieren die zusätzlichen Ebenen der Tasten auf dem Numberpad. Nur nicht die zusätlichen Ebenen von NumLock und / funktionieren nicht.

Bei * z.B ergibt die vierte Ebene × und die fünfte Ebene ⊙, ganz so wie es sein soll. Aber bei / gibt einfach nur ein / statt ein ∕ in der vierten Ebene und auch einfach nur ein / statt ein ⌀. Das erste mag aussehen wie ein normaler Slash, aber es ist ein anderes Zeichen.
Das wirkt vielleicht alles etwas pedantisch, aber trotzdem wäre es schön, wenn es funktionieren würde. Und sowieso ist es komisch, dass es sich anders verhält als beim *. Vielleicht liegt das am Scan-Code, denn im Code werden / und * sonst genau gleich behandelt.

Bei NumLock sollte ausserdem in der vierten Ebene ein ≠ und in der fünften Ebene ein ≈ erscheinen. Aber stattdessen macht es NumLock aus statt Zeichen auszugeben. Hier ist definitiv der Scan-Code Problematisch, das haben wir ja schon herausgefunden, dass NumLock und Pause den selben Scan-Code haben. Nur kenne ich mich zu wenig gut aus um das selber zu fixen.

Liebe Grüsse
Dario

**Comment by MaxGyver83** [comment]
Hallo Dario,

die "/"-Taste im Nummernblock sollte im neuen Bugfix-Release funktionieren:
https://github.com/MaxGyver83/neo2-llkh/releases/tag/v0.5.1

Grüße
Max

**Comment by DarioViva42** [comment]
Perfekt Max

Es funktioniert nun. Schade gibt es kein teilweise schliessen Knopf. So muss halt diese Nachricht Dank genug sein.
Ich habe aus Neugier in den Code geschaut. Warum musst extra für diese Taste etwas anderes machen?
Aber hauptsache es funktioniert. Es hat irgendwas mit dem #31 zu tun, gell? Ganz komisch, ich hoffe, das war nicht mein Fehler.
Ich habe aber noch ein paar zusätzliche Tasten gefunden, die nicht ganz funktionieren. Aber da ist es nur die sechste Ebene, die nicht geht. ⊆⊷⊇ für 456, □ für 0 und ′′ für , .
Hier siehst du nochmal die Graphik für den Vergleich.
https://neo-layout.org/grafik/druckvorlage/neo-druckvorlage.pdf

Und noch eine klitzekleine Bemerkung. https://github.com/MaxGyver83/neo2-llkh/blob/6b211ff75760438e147c2b196f68904610debc84/src/main.c#L269
Hier habe ich <kbd>Shift</kbd>+<kbd>0-Numpad</kbd> auf ␣ gemapped.
Aber eigentlich sollte es, so wie ich nun stark vermute, ein Leerzeichen sein.
Welches weiss ich nicht, aber nach DIN 5008 kommt zwischen einer Zahl und einer Einheit ein Leerzeichen.
Bringt also sicher mehr als ein ␣.

Viele Grüsse
Dario

**Comment by MaxGyver83** [comment]
> Warum musst extra für diese Taste etwas anderes machen?

Die Bindestrich-Taste ist ja im US/QWERTY-Layout die `/`-Taste. Dummerweise haben diese Taste und `/` im Ziffernblock den gleichen Scan-Code (`53` bzw. `0x35`). Beim Ziffernblock ist aber zusätzlich das extended-Bit gesetzt: [Liste der ScanCodes](http://www.winfaq.de/faq_html/Content/tip1500/onlinefaq.php?h=tip1576.htm). `35 E0` entspricht 53 (dezimal) mit extended-Bit.

>  Aber eigentlich sollte es, so wie ich nun stark vermute, ein Leerzeichen sein.

OK, dann änder ich das. Ich mach aber nicht extra dafür ein neues Release.

**Comment by DarioViva42** [comment]
Ich habe das Gefühl, dass jedes Problem, das es hier zu lösen gibt, irgendwie etwas mit ScanCodes zu tun hat. Hoffentlich hat es irgendwo einen Vorteil gemacht, denn sonst wäre dieses extended Bit nur da um alle zu nerfen. 🤯

> OK, dann änder ich das. Ich mach aber nicht extra dafür ein neues Release.

Ja klar, das habe ich schon nicht erwartet 😉
