### ISSUE TITLE
Fehlendes Neo2-Semikolon in v0.5

### ISSUE THREAD

**Issue by thomasgm1971** [MaxGyver83/neo2-llkh#31]
Hallo und einen guten Morgen!

In der aktuellen Release v0.5 unter Neo2 funktioniert das Semikolon auf dem qwertz-Bindestrich bzw. neo-j nicht. Normalerweise erscheint es in Verbindung mit Mod3 oder mit Mod4. Statt dessen erscheinen ÷ oder  ∕ . So kann unter der Neo2-Belegung momentan gar kein Semikolon eingegeben werden.

Einen schönen Sonntag Euch noch, Thomas

**Comment by thomasgm1971** [comment]
gedrückt wurden als neo2: j, mod3+j, mod4+j

 Layout: neo
 customLayout:
 symmetricalLevel3Modifiers: 0
 returnKeyAsMod3R: 0
 tabKeyAsMod4L: 0
 capsLockEnabled: 1
 shiftLockEnabled: 0
 level4LockEnabled: 0
 qwertzForShortcuts: 0
 swapLeftCtrlAndLeftAlt: 1
 swapLeftCtrlLeftAltAndLeftWin: 0
 supportLevels5and6: 0
 capsLockAsEscape: 1
 mod3RAsReturn: 1
 mod4LAsTab: 1
 debugWindow: 1

key down      | sc:053 vk:0xBD flags:0x00 extra:0
 mapped       | sc:053 -->j [0x006A] (level 1)
injected down | sc:053 vk:0x4A flags:0x10 extra:0 (J)
key up        | sc:053 vk:0xBD flags:0x80 extra:0
 mapped       | sc:053 -->j [0x006A] (level 1)
injected up   | sc:053 vk:0x4A flags:0x90 extra:0 (J)

key down      | sc:058 vk:0x14 flags:0x00 extra:0 (M3 left)

key down      | sc:053 vk:0xBD flags:0x00 extra:0
 mapped       | sc:053 -->¸ [0x00F7] (level 3)
injected down | sc:247 vk:0xE7 flags:0x10 extra:0
key up        | sc:058 vk:0x14 flags:0x80 extra:0 (M3 left)
key up        | sc:053 vk:0xBD flags:0x80 extra:0
 mapped       | sc:053 -->j [0x006A] (level 1)
injected up   | sc:053 vk:0x4A flags:0x90 extra:0 (J)

key down      | sc:086 vk:0xE2 flags:0x00 extra:0 (M4 left [<])

key down      | sc:053 vk:0xBD flags:0x00 extra:0
 mapped       | sc:053 -->§ [0x2215] (level 4)
injected down | sc:8725 vk:0xE7 flags:0x10 extra:0
key up        | sc:053 vk:0xBD flags:0x80 extra:0
 mapped       | sc:053 -->§ [0x2215] (level 4)
injected up   | sc:8725 vk:0xE7 flags:0x90 extra:0
key up        | sc:086 vk:0xE2 flags:0x80 extra:0 (M4 left [<])

und noch eine kuriosität, keine ahnung ob das von bedeutung ist. in issue #28 schreibt dario von fehlendem mapping beim numpad-/. die beiden zeichen, die beim mod3 oder mod4 + j erscheinen, entsprechen denen, die mit mod3 oder mod4 auf das numpad-/ gehören. 

thomas

**Comment by MaxGyver83** [comment]
Hi Thomas,

danke für den Hinweis. Ich hab den Fehler gefunden. Ich erzeuge ein neues Release.

Grüße
Max

**Comment by MaxGyver83** [comment]
Hier ist das neue Release: https://github.com/MaxGyver83/neo2-llkh/releases/tag/v0.5.1
