### ISSUE TITLE
Compose-Taste und Drehen-Taste

### ISSUE THREAD

**Issue by DarioViva42** [MaxGyver83/neo2-llkh#34]
Hallo @MaxGyver83 

Lang Zeit habe ich mich gefragt, was das ♫ Zeichen auf der Tabulatortaste sollte bei dem [Neo Layout](https://neo-layout.org/grafik/druckvorlage/neo-druckvorlage.pdf) sollte.
Jetzt weiss ich es, heureka, bin zufällig darauf gestossen. Es ist die Compose-Taste. Sie dient dem Erstellen von Ligaturen. So kann mit <kbd>Mod3</kbd>+<kbd>Tab</kbd>(♫)+<kbd>f</kbd>+<kbd>i</kbd> = `ﬁ`
[Hier](https://git.neo-layout.org/neo/neo-layout/wiki/Compose) kannst du noch die Liste sehen mit den unterstützten Ligaturen. Komischerweise ist `œ` nicht dabei, jedoch sollte es schon dabei sein, wie man [hier](https://www.wikiwand.com/de/%C5%92) sehen kann. Diese Ligatur wird im Französischen benutzt, ist also schon einigermassen wichtig. Da kommt mir sttmedia in den Sinn, kennst du diese Seite? Da kannst du die Bigramme, Trigramme und zusätzliche Zeichen für verschiedene Sprachen einsehen. Darunter für [Deutsch](https://www.sttmedia.de/buchstabenhaeufigkeit-deutsch), [Englisch](https://www.sttmedia.de/buchstabenhaeufigkeit-englisch), [Französisch](https://www.sttmedia.de/buchstabenhaeufigkeit-franzoesisch) und [Spanisch](https://www.sttmedia.de/buchstabenhaeufigkeit-spanisch). Auf Linux gibt es so eine Compose-Taste, aber nicht auf Windows. Da wird die Umsetzung wohl etwas schwieriger. Aber ist sicher sinnvoller als dass Tabulator in der dritten Ebene ein Tabulator bleibt.
Ein ähnliches cooles Feature, welches von diesem Treiber leider auch nicht unterstützt wird, ist die [↻-Taste](https://www.wikiwand.com/de/Neo_(Tastaturbelegung)#/Zeichenvielfalt_und_Typografie). Zum jetzigen Zeitpunkt macht die Taste wie die Tabulator-Taste das gleiche wie in der ersten Ebene. Mit der lassen sich Zeichen umdrehen. Die ist bei der ^-Tod-Taste. Z. B. <kbd>Mod3</kbd>+<kbd>^</kbd>(↻)+<kbd>a</kbd> = `ɐ`
Vielleicht helfen dir da diese Seiten weiter: [Font Generator](https://fsymbols.com/generators/aboqe-flip/) und [Upsidedowntext](http://www.upsidedowntext.com/unicode)
Mir ist schon klar, dass diese Tod-Tasten nicht lebensnotwendig sind, aber es wäre trotzdem schön sie zu haben.

**Comment by DarioViva42** [comment]
Hallo Max

Da ist noch der Wikiartikel zu der Compose Taste: https://www.wikiwand.com/de/Compose-Taste
Interessanterweise sind da noch viel mehr Kombinationen dabei, auch Umlaute und so.
Und die Neo-Leute haben auch schon diskutiert, ob es auch möglich sein soll, diese auch in umgekehrter Reihenfolge eingetippen zu können. Dann wärs ein noch grösserer Aufwand. Wer weiß, vielleicht ist dir in nächster Zeit einmal langweilig, dann kannst du's einbauen.

Und das habe ich letztes Mal nicht beantwortet, aber ein Forum auf deiner Seite wäre schon noch praktisch. Ich habe schon noch weitere Ideen für dich parat. 👍

Liebe Grüße mit Scharf-S

Dario

**Comment by MaxGyver83** [comment]
Hallo Dario,

ja, Compose kann der Treiber nicht.

Ehrlich gesagt benutze ich ja fast nie Windows. Nur bei der Arbeit muss ich das manchmal. Deshalb habe ich auch diesen Treiber erweitert. Vor ein paar Wochen habe ich dieses Programm entdeckt: [KMonad](https://github.com/david-janssen/kmonad). Das benutze ich unter Linux jetzt dauerhaft als VOU-Treiber. Unter Windows kann man damit auch arbeiten, obwohl es noch ein paar Bugs gibt. Ich hab das mal in der [AdNW-Diskussionsgruppe vorgestellt](https://groups.google.com/forum/#!topic/adnw/a7wCT90jlOE). Auf meiner Homepage habe ich es auch schon [angepriesen](https://maximilian-schillinger.de/modifier.html). Bei KMonad ist es jedenfalls so, dass man unter Windows ein separates Programm für eine Compose-Funktion benötigt: [WinCompose](http://wincompose.info/). Das könntest du ja mal ausprobieren.

**Comment by DarioViva42** [comment]
Hallo Max

das sieht ja sehr interessant aus, kmonad und wincompose werde ich mir sicher mal anschauen, wenn ich etwas zeit habe. kannst ja mal eine Anleitung für dummies machen, wie man dein vou, an das ich mich schon fast gewöhnt habe, in dem kmonad einrichten kann.

Vielen Dank
Dario

**Comment by MaxGyver83** [comment]
KMonad kann man [hier](https://github.com/david-janssen/kmonad/releases/tag/0.4.1) einfach als Binary herunterladen. Meine [VOU-Konfig](https://github.com/david-janssen/kmonad/tree/master/keymap/user/MaxGyver83) findest du im offiziellen KMonad-Repo (leicht veraltet bzgl. der Modifier; ich lad die neuste Konfig demnächst in mein dotfiles-Repo). Dann musst du noch das Tastaturlayout auf Englisch (USA/International) stellen (weil in der KMonad-Konfiguration z.B. ein `/` für die `/`-Taste steht und die mit einem deutschen Layout ein `-` erzeugt). Dann kannst du es in `cmd`/`Powershell` mit `C:\Pfad\zu\KMonad C:\Pfad\zur\Konfig` starten.

Wahrscheinlich widme ich KMonad noch eine Extra-Seite auf meiner Homepage.

**Comment by DarioViva42** [comment]
https://github.com/david-janssen/kmonad/issues/84#issuecomment-696075495
das ist ja mega der zufall, erst vor kurzer zeit hast du auch compose auf windows benutzen wollen.

und danke für die anleitung. beim durchstöbern habe ich deinen eintrag schon entdeckt.

**Comment by DarioViva42** [comment]
jetzt habe ich mal wincompose ausprobiert. leider behandelt er die tasten wie in qwertz. auch wenn ich die einstellungen so ändere, dass es eigentlich funktionieren sollte. also die einstellung mit den injizierten tasten meine ich.
![grafik](https://user-images.githubusercontent.com/45972949/95768204-40762d80-0cb6-11eb-9c06-767a240c7c8b.png)

hast du es hinbekommen mit kmonad, dass es die vou keys beachtet? Vielleicht hilft dir diese Einstellung.

**Comment by MaxGyver83** [comment]
> jetzt habe ich mal wincompose ausprobiert. leider behandelt er die tasten wie in qwertz. auch wenn ich die einstellungen so ändere, dass es eigentlich funktionieren sollte. also die einstellung mit den injizierten tasten meine ich.

Ist bei mir leider genauso.

> hast du es hinbekommen mit kmonad, dass es die vou keys beachtet? Vielleicht hilft dir diese Einstellung.

Nein, ich hab es noch nicht hinbekommen. Auch nicht mit dieser Einstellung. David meinte ja, er hat Ideen, wie man das lösen könnte. Ich hab mich dann auch nicht weiter beschäftigt. Ich wollte nur mal testen, wie gut KMonad in Windows mit meiner Konfiguration funktioniert.

**Comment by DarioViva42** [comment]
hey @MaxGyver83 und andere
ich habe eine Lösung gefunden. Mit dem [Microsoft Keyboard Layout Creator](https://www.microsoft.com/en-us/download/details.aspx?id=102134) kann man ein Layout erstellen, bei dem WinCompose funktioniert. Der bietet nicht mod3 und mod4 keys an, daher benutze ich bei meinem Layout altgr als mod3. mit den angefügten Dateien kann man das Layout laden.
Damit mod3 auf caps lock und ä liegt, müssen diese noch separat remapped werden. mit [sharp keys](https://github.com/randyrants/sharpkeys) kann man das machen. Theoretisch könnte man auch caps lock als mod4 benutzen, allerdings toggeled der halt, daher habe ich darauf verzichtet, so dass es insgesamt nur 4 Ebenen gibt. So bleibt die < Taste frei. Daher habe ich erst j auf diese günstigere Position verschoben. Dann habe ich mich ein wenig ausgetobt und ein neues Layout gesucht. Bei dieser Variante bleiben die shortcuts am gleichen ort, und werden nicht remapped.
[boy.zip](https://github.com/MaxGyver83/neo2-llkh/files/5396447/boy.zip)
