### ISSUE TITLE
~ vs  ̃

### ISSUE THREAD

**Issue by DarioViva42** [MaxGyver83/neo2-llkh#35]
Hi @MaxGyver83 

Wegen den Umlauten gibts auch noch etwas, das man hoffentlich besser machen kann.
Wie du gesagt hast muss das Todzeichen manchmal vor und manchmal nach dem dazugehörigen Zeichen eingegeben werden.
> • Die meisten toten Tasten werden unterstützt: ^ ` ´ ̧ ̌ ~ ° ̇ (teilweise muss die tote Taste vor, teilweise nach dem Buchstaben gedrückt werden)

Das ist ja nicht sehr ideal. Die Todtasten die vor dem Zeichen gedrückt werden sind meiner Meinung nach den anderen überlegen. Sie sorgen dafür, dass das Zeichen, das am Schluss im Text steht, nur ein einzelnes Zeichen ist. Mit  ̃  wird nicht ein einzelnes Zeichen mit Umlaut erstellt. Es sieht nur so aus. Das kann leicht mit Python überprüft werden.
Hier habe ich zweimal ein N mit Tilde: ñ und ñ.
Mit folgendem Code sieht man den Unterschied, das eine ist ein echtes N mit Tilde, das andere ist Fake.
```python
[ord(e) for e in 'ñ und ñ']
[241, 32, 117, 110, 100, 32, 110, 771]
```
Das echte ist ein einzelnes 241 und das falsche ist ein 110 plus 771.
Auch beim kopieren in ein Terminalfenster mit Monospace-Schrift fällt der Unterschied schnell auf.
Das echte Tilde kann in Deutsch(Deutschland) nicht als Todtaste verwendet werden, im Gegensatz zu Deutsch(Schweiz) wo es möglich ist. Siehe [hier](https://www.wikiwand.com/en/Tilde?redirect=no#/Keyboards). Vielleicht kann man das irgendwie umgehen.
Also was ich auf eine komische Art und Weise erklären möchte, kann man noch einfach verständlich [hier](https://www.wikiwand.com/en/Precomposed_character#/Comparing_precomposed_and_decomposed_characters) nachlesen. Also wie gesagt, meiner Meinung nach ist precomposed der bessere Weg, aber es kann auch sein dass du mir da wiedersprichst. Aber eigentlich sollten wenigstens alle precomposed oder alle decomposed sein. Weil so wie es jetzt ist, ist es ein Mischmasch ;)

precomposed: `` ´ ` ^ ``
decomposed:  `̃  ̧  ̌   ̊   ̇  ̣   ̄   ̉  `
wird als einzelnes Zeichen dargestellt: ` ῾ ᾿ ¨ ˝ ̷  `
funktioniert gar nicht: ` ̆ `

In KMonad wird das eventuell besser funktionieren, da im Englischen Tastaturlayout mit ctrl+~ ein totes ~ eingefügt werden kann (Wahrscheinlich). Wie es um die übrigen Todtasten steht, weiss ich nicht.

**Comment by MaxGyver83** [comment]
Hi @DarioViva42 ,

sorry für die späte Antwort. Ich hab mich erst heute damit beschäftigt.

Deinem [Link](https://www.wikiwand.com/en/Tilde?redirect=no#/Keyboards) zufolge ist die Tilde je nach Tastaturlayout entweder ein tote Taste (z.B. Schweiz) oder sie fügt die Tilde sofort ein (z.B. Deutschland).

Wenn du [`~`](https://www.compart.com/de/unicode/U+007E) + `n` = [`ñ`](https://www.compart.com/de/unicode/U+00F1) willst, kannst du natürlich einfach das Schweizer Tastaturlayout einstellen (und dann `neo2-llkh` starten). Dann ist die Tilde auf Ebene 3 automatisch eine tote Taste.

Die Alternative wäre, die Tottasten-Funktion in `neo2-llkh` nachzubilden, d.h. wenn zum Beispiel eine Tilde eingegeben wird, erst einmal nichts auszugeben, und je nachdem ob danach ein `a`, `i`, `n`, `o` oder `u` (oder ein entsprechender Grossbuchstabe) kommt, den fertig zusammengesetzten Buchstaben auszugeben. (Dann aber nur für die "zweite" Tilde, die jetzt als "[Kombinierende Tilde](https://www.compart.com/de/unicode/U+0303)" umgesetzt ist, in deinem Beispiel dezimal `771`.) Da es aber einige Diakritika gibt, wären das ganz schön viele Sonderfälle, für Zeichen, die im deutschsprachigen Raum so gut wie nie benutzt werden. Deshalb schreib ich das jetzt mal nicht ganz oben auf meine ToDo-Liste 😬. (In NeoVars ist es so gelöst: [Hier](https://git.neo-layout.org/neo/neo-layout/src/branch/master/windows/neo-vars/src/compose.generated.ahk#L1195) ist z.B. definiert, dass `~` (U+007E) + `n` (U+006E) = `ñ` (U+00F1) ist.)

In KMonad wird ja für seltene Zeichen (welche die nicht im Windows-Tastaturlayout enthalten sind) auf [WinCompose](http://wincompose.info/) zurückgegriffen. Das kann man natürlich auch zusammen mit `neo2-llkh` verwenden. Dann wäre z.B. `RechteStrg` + `~` + `n` = `ñ` (alle Tasten nacheinander gedrückt).
