### ISSUE TITLE
System Tray Icon Exit geht manchmal nicht

### ISSUE THREAD

**Issue by maribox** [MaxGyver83/neo2-llkh#43]
Das kommt öfters vor, wenn man es mal durch klicken ein- und ausschaltet.
Dann geht das Rechtsklick -> Exit zwar nicht mehr, aber der Prozess läuft immer noch und man kann noch ein- und ausschalten durch Linksklick.

Einstellungsmöglichkeiten im Rechtsklickmenü wären natürlich auch phänomenal.

**Comment by MaxGyver83** [comment]
Alles klar, danke für den Hinweis! Ich werde versuchen, das zu reproduzieren (und dann zu beheben).

**Comment by MaxGyver83** [comment]
Behoben in Commit 153da0a5bb48614a9743ff58acb846e605393ba9.
