### ISSUE TITLE
Mod3 Verschiebung sinnvoller gestalten

### ISSUE THREAD

**Issue by maribox** [MaxGyver83/neo2-llkh#44]
![image](https://user-images.githubusercontent.com/70728036/126039137-1e59f9a4-c843-4601-9325-5a0f38a2feb4.png)
In deinem VOU Layout wird M3 deutlich sinnvoller verschoben, als mit neo llkh, wenn man neo benutzt. Das y wandert nach oben und ß nach rechts. Damit ist y leichter zu treffer als ß, wie du ja auf deiner Website ja auch selbst meinst: 
![image](https://user-images.githubusercontent.com/70728036/126039177-393015b2-cde6-4104-b6d5-bade7829d942.png)

Wäre toll wenn es eine zusätzliche Option dafür gäbe oder symmetricalLevel3Modifiers es einfach besser verschiebt als jetzt.

**Comment by MaxGyver83** [comment]
## Kurze Antwort

Ja, wie du schon geschrieben hast, sind wir uns einig, dass es sinnvoll ist, dass die Taste oben rechts (QWERTZ: `ü`) besser erreichbar ist als die Taste in der Mitte ganz rechts (QWERTZ: `#`).

Ich bin allerdings gegen eine "automatische" Vertauschung von Buchstabentasten bei Verwendung von `symmetricalLevel3Modifiers`, weil ...

- ... andere Nutzer vielleicht doch lieber die `#`-Taste als die `ü`-Taste benutzen,
- ... andere Nutzer (inkl. mir) bei der Definition ihres Layouts `symmetricalLevel3Modifiers` schon berücksichtigt haben und die Taste der oberen Reihe auch da bleiben soll.

## Philosophische Antwort

Ja, man könnte hier einen neuen Parameter einführen, zum Beispiel `swapUeAndHashKey=1`.

Wenn es nur eine Hand voll Optionen gibt, ist es am einfachsten, dafür ein paar Parameter zu definieren (sowas unmissverständliches wie zum Beispiel `supportLevels5and6=1`). Inzwischen gibt aber schon recht viele Parameter und immer wieder gibt es neue Ideen, welche Tasten man vertauschen könnte oder dass eine bestimmte Tasten eine andere Funktion haben kann, je nachdem, ob sie angetippt oder gehalten wird.

Deshalb möchte ich davon wegkommen, für jeden Sonderfall einen neuen Parameter einzuführen. Ich würde meine Zeit lieber nutzen, die Konfigurationsdatei noch flexibler zu machen. Dass man zum Beispiel statt 

```
mod3RAsReturn=1
```

schreiben kann:

```
Ä=Return
Ä=ModTap(mod3R)
```

Oder so ähnlich (mit anderer Syntax). Dann könnte jeder sein Tastatur-Layout viel freier konfigurieren.

Für die hier angesprochene Änderung ist es zum Glück ja schon so, dass jeder selbst die Buchstaben vertauschen kann, wie er will. Also zum Beispiel:

```
customLayout=xvlcwkhgfqyuiaeosnrtdßüöäpzbm,.j
```

(=Neo mit `y` oben rechts und `ß` in der Mitte rechts)
