### ISSUE TITLE
LMod3 und Neo-Y funktionieren nicht

### ISSUE THREAD

**Issue by Rojetto** [MaxGyver83/neo2-llkh#45]
Hallo 😃,

wenn ich die EXE und settings.ini des Release v0.6.2 lade und starte (keine Änderungen), funktionieren zwei Sachen nicht:
1. Die Taste QWERTZ-Ä bzw. Neo-Y erzeugt kein Zeichen, sondern nur ein RShift-Event
2. LMod3 (auf Capslock) wechselt nicht auf Ebene 3 sondern erzeugt Großbuchstaben. Als Event sehe ich beim Drücken LShift

Keine Eile damit, bin nicht akut auf den Treiber angewiesen, sondern wollte eigentlich nur die Tap-Modifier ausprobieren. Vielleicht betrifft es aber auch andere Leute.

**Comment by MaxGyver83** [comment]
Oh, wie doof! Ich hab genau dieses Verhalten nur für mich im Code umgesetzt, hab es aber aber beim letzten Commit weggelassen. In der exe ist es jetzt vermutlich trotzdem drin. Ich kompilier nochmal neu und aktualisiere die exe.

Danke für den Hinweis!

**Comment by MaxGyver83** [comment]
Ich hab die EXE ausgetauscht.
