### ISSUE TITLE
Caret symbol ( ^ ) no longer works in PowerShell Core

### ISSUE THREAD

**Issue by Snaptags** [MaxGyver83/neo2-llkh#47]
Mod3 + t no longer prints a ^ in PowerShell Core (but works in any other application)

Last version where it did work was v0.5.2.

(PowerShell 7.2.0, Windows 10)

**Comment by MaxGyver83** [comment]
Thanks for your feedback. I'll check it.

**Comment by MaxGyver83** [comment]
I have installed PowerShell 7.2.0 and I can reproduce the issue. It looks like this issue was introduced by commit 51fdd3a which fixed #26 (_Backtick and caret insert just a space (only in Neovim)_).
When I just undo this change, the caret will be broken in Neovim again. This means, I'll have to investigate how to make the caret work both in in Neovim and PowerShell Core.

**Comment by Snaptags** [comment]
Other characters on Layer 3 seem to be affected, too:
… (Q)
ſ (ü)
̷  (*)

` (B)

And the entire number row ¹²³›‹ ¢¥‚‘’—

(But all of those are not really important in a shell, the missing ^ is bad because of HEAD^ vs HEAD~1 in git :-)

**Comment by MaxGyver83** [comment]
The characters that don't work are those sent as Unicode characters. The alternative is emulating the key press (combination) that emits the desired character usually. But that's only possible if that character is available in the system keyboard layout (QWERTZ). We can emit a caret and backtick by sending the corresponding dead keys followed by a space. But there is no workaround for …, ſ,  ̷  and so on (except using an external tool like WinCompose but this didn't work either in a quick test).

I have added a new option called `preferDeadKeyPlusSpace` in commit bc1236e7d9043c02c33d78b8ceb0101f85d4674c. This should make caret and backtick work in PowerShell Core 7.2. Would you mind testing it?

[neo-llkh.zip](https://github.com/MaxGyver83/neo2-llkh/files/7699071/neo-llkh.zip)

Just set `preferDeadKeyPlusSpace=1` in your `settings.ini` or add it as command line parameter.

**Comment by Snaptags** [comment]
Thanks, I can confirm the change (and enabling the new option) fixes dead keys in PowerShell. BUT it also breaks my "ä" key, it no longer prints "y" :(

**Comment by MaxGyver83** [comment]
Oh, that's bad! And strange. Thanks for testing. I'll check again.

**Comment by MaxGyver83** [comment]
You are right! The build I attached contained some uncommitted changes which I didn't want to include. (The "ä" is another shift key in that build.)

Could you try again with this version?
[neo-llkh.zip](https://github.com/MaxGyver83/neo2-llkh/files/7706682/neo-llkh.zip)

**Comment by Snaptags** [comment]
That's much better, thanks :-)

**Comment by MaxGyver83** [comment]
Good to hear! I'll create a new release.
