### ISSUE TITLE
Strg Hotkeys funktionieren unzuverlässig wenn Strg, Win, Alt geswitched werden

### ISSUE THREAD

**Issue by maribox** [MaxGyver83/neo2-llkh#49]
Wenn man die Option aktiviert, dass man die linken 3 Buttons switched (Strg, Win, Alt), kommt es bei mir sehr häufig vor, dass Strg-Hotkeys einfach nicht mehr funktionieren.

Ich habe leider nur eine Sache gefunden, bei der sich das bei mir zufällig reproduzieren lässt und das ist, wenn man die QWERTZ-Alt und QWERTZ-Windows Taste gleichzeitig drückt. Dann funktioniert die QWERTZ-Alt, also Strg Taste nicht mehr. Komischerweise ist das einzige, das das zuverlässig wieder funktionieren lässt, zweimal die QWERTZ-Strg Taste zu drücken.

Leider kann man so nicht arbeiten, wenn man kein Strg zur Verfügung hat und das Vertauschen ist echt hilfreich. Wäre toll, wenn mal jemand probieren könnte, das zu reproduzieren 👍🏻

**Comment by maribox** [comment]
Noch ein paar Ergänzungen:
Ich habe ein Windows 11 System, benutze bone, das Programm läuft im Admin Mode und die Debug Konsole zeigt auch, dass es die Strg-Anschläge erkennt. Und ich habe noch etwas herausgefunden: Um die Funktion der Strg-Taste ausfallen zu lassen reicht anscheinend schon einfaches betätigen der QWERTZ-Windows Taste, also der Alt-Taste.

**Comment by maribox** [comment]
Und das ganze betrifft auch nicht den Alt-Ctrl Switch, sondern nur den 3 Tasten-Switch.

**Comment by MaxGyver83** [comment]
Danke für die Rückmeldung!
Ich versuch das zu reproduzieren. Da ich Windows so gut wie nie benutze, und wenn doch, dann (inzwischen) ohne die Vertauschung von Ctrl, Win und Alt, bekomme ich solche Fehler gar nicht mit.

Falls du eine schnelle Lösung brauchst: Ich hab mal eine Zeit lang [SharpKeys](https://github.com/randyrants/sharpkeys) verwendet. Damit kannst du Ctrl, Alt und die Windows-Taste dauerhaft vertauschen. Das gilt dann natürlich auch, wenn `neo2-llkh` nicht läuft.

**Comment by thomasgm1971** [comment]
ich habe (nur) ctrl und alt vertauscht. habe eben noch einmal geschaut, ich
benutze auch sharpkeys und habe in neo2-llkh swapLeftCtrlAndLeftAlt=0
gesetzt. ich erinnere mich schwach, ich hatte auch probleme beim ctrl und
alt vertauschen (also mit neo2-llkh), da es oft zu alt-hängern kam. und
sharpkeys löste das problem dauerhaft!

Am Do., 9. Dez. 2021 um 16:20 Uhr schrieb Max Schillinger <
***@***.***>:

**Comment by MaxGyver83** [comment]
> Und ich habe noch etwas herausgefunden: Um die Funktion der Strg-Taste ausfallen zu lassen reicht anscheinend schon einfaches betätigen der QWERTZ-Windows Taste, also der Alt-Taste.

Danke für die detaillierte Beschreibung! Ich konnte das reproduzieren. Commit c8f7b2b93a9d3549b14b28d2bd801f495fba5b1e behebt diesen Fehler.
