### ISSUE TITLE
Keys don't work in win 11 emoji menu. 

### ISSUE THREAD

**Issue by JanB987** [MaxGyver83/neo2-llkh#51]
The keys don't seem to function in the search of the win 11 emoji search menu (win + ü in GER). See attached image: 
<img width="260" alt="image" src="https://user-images.githubusercontent.com/49116853/146651509-638d79c7-5be8-4d3b-b163-247443e498da.png">

**Comment by MaxGyver83** [comment]
Do you have admin rights? Could you try starting `neo-llkh.exe` with admin rights?

**Comment by JanB987** [comment]
Just tried but sadly without any luck. Still no response. Just the number keys work.

**Comment by MaxGyver83** [comment]
Could you try again with `neo-llkh.exe layout=qwertz`? (Or `layout=qwertz` in `settings.ini`.) Unfortunately, I can't test it because I don't have Windows 11.

**Comment by JanB987** [comment]
Will do, happy to help on the project. 
**Results**: Sadly, also no success. 

Just to confirm that I did the right setting see image. I executed the exe in admin mode. 
<img width="496" alt="image" src="https://user-images.githubusercontent.com/49116853/146715827-f4020720-d744-49cf-8a78-8a75e7544a55.png">

**Comment by MaxGyver83** [comment]
OK, then it's not a permission problem. And virtual key codes not matching scan codes is not the reason either.
I suppose that the Windows 11 emoji search menu just ignores "injected" key events. This is something I can't change. `neo-llkh`'s key event are never original key events but always injected ones. In this case you should open a bug report for Windows 11.

**Comment by JanB987** [comment]
Noted and will do. Thanks for the effort and great work on the program in general!
