### ISSUE TITLE
Mapping inaktiv nach Win + L relogin

### ISSUE THREAD

**Issue by mkxwell** [MaxGyver83/neo2-llkh#52]
Hi,
hat man die Option 'qwertzForShortcuts' aktiviert und benutzt die Tastenkombination Win + L um den Bildschirm zu sperren, so registriert das Programm den Release der Win-Taste nicht mehr und benutzt nach erneutem Login nicht mehr das Mapping, da es noch davon ausgeht, dass die Win-Taste gedrückt ist.
Ich habe mich jetzt noch nicht weiter mit Code beschäftigt, mir fällt aber auch spontan nicht ein wie man das sauber gelöst bekommen würde.
Ein Workaround wäre beim Deaktivieren und erneuten Aktivieren durch Klicken auf das Tray Icon den Status zurückzusetzen.

**Comment by MaxGyver83** [comment]
Hast du neo2-llkh mit Admin-Rechten ausgeführt? (Das könnte schon die Lösung sein.)

Ansonsten bekommt die Windows-Taste auch wieder gelöst, indem man sie nochmal antippt. Hast du das mal probiert?

**Comment by mkxwell** [comment]
Die Admin-Rechte haben nichts geändert.

Nochmaliges Antippen hilft. Aus dummer Angewohnheit sperre ich mit der rechten Windows-Taste und hatte versucht mit der Linken zu lösen, bis mich dein Kommentar auf den richtigen Pfad gebracht hat...
Vielen Dank!
