### ISSUE TITLE
Strg+W & Strg+T does not seem to work in Chrome

### ISSUE THREAD

**Issue by arBmind** [MaxGyver83/neo2-llkh#8]
Am I doing something wrong here?

**Comment by MaxGyver83** [comment]
I have just tested it (with the latest version of Chrome) and it worked for me.

Could you post your `settings.ini`?

And could you activate the debug window (with `debugWindow=1`) and post the output you get for Ctrl-W and/or Ctrl-T?

**Comment by arBmind** [comment]
Now that I run it again, it seems to work for now.

Something was wrong… I will investigate further.

Thanks again for the good work!
